import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useRef} from 'react'



export default function Home() {
 
  const refs =useRef([])

  function cardClick(event){
    let slider =event.currentTarget.nextElementSibling.classList
    slider.toggle('invisible')

    let card = event.currentTarget.offsetParent.classList
    card.toggle('bg-base-100')
    
    console.log(refs.current[event.currentTarget.offsetParent.dataset.key])

    let audio = event.currentTarget.nextElementSibling.firstChild
    if (audio)
        audio.paused ? audio.play() : audio.pause()
        audio.volume = 0.5
    
  }

  

function handleClick(element,volume=0.5){
  let slider =element.nextElementSibling.classList
    slider.toggle('invisible')

    let card = element.offsetParent.classList
    card.toggle('bg-base-100')
    
    console.log()

    let audio = element.nextElementSibling.firstChild
    if (audio)
        audio.paused ? audio.play() : audio.pause()
        audio.volume = volume
  console.log(element.currentTarget)
}

function recomendationClick(){
  let recomendation = ['rain','thunderstorm','train']
  
  recomendation.forEach((item)=>{
    handleClick(refs.current[item])
    console.log(refs.current[item])
  })
  
}

  function volumeSlider(event){
    let slider = event.currentTarget

    let audio = slider.previousSibling

    if (audio)
        audio.volume = slider.value / (slider.max - slider.min)

    
  }

  let recomendations = ['item 1','item 2','item 3', 'item 4','item 5']
  let recomendationList = recomendations.map((recomendation,index)=>{
    return <button onClick={recomendationClick} className='btn btn-outline btn-sm text-s uppercase rounded-full '> {recomendation} </button>
  })

  let sounds = ['rain','thunderstorm','forest','waterstream','seaside','fire','leaves','fan','coffee','wind','water','train','brownnoise','pinknoise','whitenoise']
  let soundList = sounds.map((sounds,index)=>{
    return <div  id='card'   data-key={sounds}  className="card p-8 mt-16 mx-4 basis-1/4 hover:bg-base-200 cursor-pointer">
              
              <figure onClick={(element)=>{handleClick(element.currentTarget)}} ref={(element) => {refs.current[sounds] = element}}><img className='w-24'  src={'/images/'+sounds+'.png'} alt="Shoes" /></figure>
              <div class="card-body p-8 pb-0 invisible">
              <audio data-key={sounds} src={'/sounds/'+sounds+'.ogg'}></audio>
              <input data-key={sounds} onClick={volumeSlider} type='range' min="0" max="100" className="range range-xs range-primary"></input>
              </div>
            </div>
  })

  
  
  return (
    <div>
      <Head>
        <title>Relaxy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='py-6 px-12 navbar bg-base-200 justify-between'>
        <div className='flex-l'>
          <h2 className='normal-case text-3xl font-bold text-primary'>
            Relaxy
          </h2>
        </div>
        
        <div className='space-x-4'>
          <button  className='btn btn-primary'>
            Login
          </button>
          <button className='btn btn-ghost'>
            Register
          </button>
        </div>
        
      </header>

      <main className='bg-base-300 min-h-screen py-16'>
        <div id='recomendation' className='space-y-4 flex flex-col mx-auto'>
          <p className='flex justify-center text-xl font-bold'>Recomendation</p>
          <div className='space-x-8 flex justify-center'>
            {recomendationList}
          </div>
        </div>

        <div id='sound' className='flex flex-wrap px-16 justify-center'>
            {soundList}
        </div>
      </main>

      
      
    </div>
  )
}
