import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


function cardclick(){
  
}



export default function Home() {

  let sounds = ['rain','forest','seaside','leaves','fan','coffee','water','train',]
  let soundList = sounds.map((sounds,index)=>{
    return <div class="card p-6 w-48 basis-1/4 hover:bg-base-200">
              
              <figure><img className='w-24'  src={'/images/'+sounds+'.png'} alt="Shoes" /></figure>
              <div class="card-body p-8 pb-0">
              <p className='uppercase flex justify-center text-sm font-bold '>{sounds}</p>
              </div>
            </div>
  })

  let activities = ['study','work','sleep','read']
  let activityList = activities.map((activity,index)=>{
    return <div class="card p-6 w-48 basis-1/4 hover:bg-base-200">
              
              <figure><img className='w-24'  src='/images/rain.png' alt="Shoes" /></figure>
              <div class="card-body p-8 pb-0">
              <p className='uppercase flex justify-center text-sm font-bold '>{activity}</p>
              </div>
            </div>
  })

  return (
    <div className=''>
      
      <Head>
        <title>Relaxy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        
      </Head>
      
      <header className='py-6 px-12 navbar bg-base-100 justify-between'>
        <div className='flex-l'>
          <h2 className='normal-case text-3xl font-bold text-primary'>
            Relaxy
          </h2>
        </div>
        
        <div className='space-x-4'>
          <label for='Login' className='btn btn-primary modal-button'>Login</label>
          <label for='Register' className='btn btn-ghost modal-button'>Register</label>
                   
          
          <input type="checkbox" id="Login" className="modal-toggle" />
          <div className="modal ml-0">
            <div className="modal-box relative text-center space-y-4">
              <label for="Login" class="btn btn-sm btn-circle absolute right-2 top-2">✕</label>
              <h3 className="text-lg font-bold mb-8">Login to your account</h3>
              <input type="text" placeholder="Email" className="input input-bordered w-full max-w-xs " />
              <input type="password" placeholder="Password" className="input input-bordered w-full max-w-xs" />
              <a className='btn btn-primary w-full max-w-xs' href=''>Login</a>
              <div className='flex justify-center space-x-1'>
                <p className=' text-xs'>Don't have an account yet?</p>
                <label for='Register' className=' text-xs underline cursor-pointer'>Register here</label>
              </div>
            </div>
          </div>


          <input type="checkbox" id="Register" className="modal-toggle" />
          <div className="modal ml-0">
            <div className="modal-box relative text-center space-y-4">
              <label for="Register" class="btn btn-sm btn-circle absolute right-2 top-2">✕</label>
              <h3 className="text-lg font-bold mb-8">Register new account</h3>
              <input type="text" placeholder="Email" className="input input-bordered w-full max-w-xs " />
              <input type="password" placeholder="Password" className="input input-bordered w-full max-w-xs" />
              <a className='btn btn-primary w-full max-w-xs' href=''>Register</a>
              
            </div>
          </div>

        </div>
        
      </header>

      <main className='hero h-full pb-48 pt-16 bg-base-100'>
      
        <div class="hero-content text-center ">
          <div class="max-w-md">
            <h1 class="text-5xl font-bold">Welcome to Relaxy</h1>
            <p class="py-6">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
            <a href='#categories' class="btn btn-primary">Get Started</a>
          </div>
        </div>

        
      
      </main>
      <div className='text-center py-4' id='categories'>
        <h1 className='normal-case  text-xl font-bold my-2'>Choose 3 sound categories</h1>
        <p className='text-xs'>and we will give you the best recomendation</p>
        <div id='sound' className='flex flex-wrap  px-16 py-6 justify-center'>
            {soundList}
        </div>
        <a href='#activities' className='btn btn-primary'>Next 😳</a>
      </div>

      <div className='text-center py-4 my-24' id='activities'>
        <h1 className='normal-case  text-xl font-bold my-2'>Choose your activities</h1>
        <p className='text-xs'>what do you use Relaxy for? </p>
        <div id='sound' className='flex flex-wrap  px-16 py-6 justify-center'>
            {activityList}
        </div>
        <a href='/app' className='btn btn-primary'>Start Listening 😁</a>
      </div>
      

      
    </div>
  )
}
