import Head from 'next/head'
import { v4 as uuidv4 } from 'uuid';
import styles from '../styles/Home.module.css'
import {createContext, useContext, useState } from 'react'
import { useRouter } from 'next/router'




export const Context = createContext({});
export let recomendationContext = createContext()

let data = require('/public/data.json')
console.log(data.category)

var axios = require('axios');  

/*function setCategory(Category){
  category = Category
  //context = {'category':category}
}

function setActivity(Activity){
  activity = Activity
  console.log(activity)
}*/
let dataCategory='asu'

export default function Home() {
  dataCategory='memek'
  const [users, setUsers] = useState();
  var [category,setCategory] = useState('this should be category');
  var [activity,setActivity] = useState('this should be activity');

  //setUsers(users('tes'))

  const usersContext = {
    "halo":"ok"
  }

  const router = useRouter()
  async function  rankRequest(){
    var data = JSON.stringify({"category":category,"activity":activity});
    console.log(category+' and '+activity)
    var config = {
      method: 'post',
      url: 'https://relaxy.azurewebsites.net/api/rank?',
      headers: { 
        'Content-Type': 'application/json'
      },
      data : data
    };

    await axios(config)
    .then(function (response) {
      console.log(config)
      
      context = {
        "id":uuidv4,
        "activity":activity,
        "ranking" : response.data
      }
      console.log(context)
    })
    .catch(function (error) {
      console.log(config)
    });
    
    
  }
  async function handleNext(){
    //setUsers
    //console.log(category+activity)
    router.push('/app')
  }

  let sounds = ['nature','people','instrument']
  let soundList = sounds.map((sounds,index)=>{
    return <div class="card p-6 w-48 basis-1/4 hover:bg-base-200">
              
              <figure><img className='w-24 cursor-pointer' onClick={(element)=>{handleClick(element.currentTarget)}} data-key={sounds} data-type="category" src={'/images/'+sounds+'.png'} alt="Shoes" /></figure>
              <div class="card-body p-8 pb-0">
              <p className='uppercase flex justify-center text-sm font-bold '>{sounds}</p>
              </div>
            </div>
  })

  let activities = ['study','work','sleep']
  let activityList = activities.map((activity,index)=>{
    return <div class="card p-6 w-48 basis-1/4 hover:bg-base-200">
              
              <figure><img className='w-24 cursor-pointer' onClick={(element)=>{handleClick(element.currentTarget)}} data-key={activity} data-type="activity" src={'/images/'+activity+'.png'} alt="Shoes" /></figure>
              <div class="card-body p-8 pb-0">
              <p className='uppercase flex justify-center text-sm font-bold '>{activity}</p>
              </div>
            </div>
  })

  function handleClick(element){
    
      let card = element.offsetParent.classList
      card.toggle('bg-base-200')
      
      let type = element.dataset.type
      let key = element.dataset.key

      
      if(type=='category'){
        setCategory(key)
        data.category=key
      }
      else{
        setActivity(key)
        data.activity=key
        //dataActivity=activity
      }
      console.log(data.category+data.activity)
  }

  return (

    
    
    <div className=''>
      <Context.Provider value={usersContext}></Context.Provider>
      <recomendationContext.Provider value='category'><recomnediton/> </recomendationContext.Provider>
      <Head>
        <title>Relaxy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        
      </Head>
      
      <header className='py-6 px-12 navbar bg-base-100 justify-between'>
        <div className='flex-l'>
          <h2 className='normal-case text-3xl font-bold text-primary'>
            Relaxy
          </h2>
        </div>
        
        
        
      </header>

      <main className='hero h-full pb-48 pt-16 bg-base-100'>
      
        <div class="hero-content text-center ">
          <div class="max-w-md">
            <h1 class="text-5xl font-bold">Welcome to Relaxy</h1>
            <p class="py-6">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
            <a href='#categories' class="btn btn-primary">Get Started</a>
          </div>
        </div>

        
      
      </main>
      <div className='text-center py-16 my-24' id='categories'>
        <h1 className='normal-case  text-xl font-bold my-2'>Choose your favorite sound category</h1>
        <p className='text-xs'>and we will give you the best recomendation</p>
        <div id='sound' className='flex flex-wrap space-x-4 px-16 py-6 justify-center'>
            {soundList}
        </div>
        <a href='#activities' className='btn btn-primary'>Next 😳</a>
      </div>

      <div className='text-center py-16 my-24' id='activities'>
        <h1 className='normal-case  text-xl font-bold my-2'>Choose your activities</h1>
        <p className='text-xs'>what do you use Relaxy for? </p>
        <div id='sound' className='flex flex-wrap space-x-4 px-16 py-6 justify-center'>
            {activityList}
        </div>
        <a  type="button" onClick={handleNext} className='btn btn-primary'>Start Listening 😁</a>
      </div>
      

      
    </div>
  )
  

}




//export const { UsersContext } = Context;